spring:
  application:
    name: chatappjn
  data:
    mongodb:
      uri: mongodb://barry75:abc123@barryonweb.com:27017/chatappdb
      database: chatappdb     
server:
  port: 8081
websocket:
  timeout-mins: 10
  check-interval-sec: 45
useridle:
  timeout-mins: 20
  check-interval-sec: 45

  
